version: '2'
services:

  base:
    build: .
    image: slackapiexport_base

  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    environment:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
      - SLACK_TOKEN
    depends_on:
      - base
    links:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./docker/slack_app:/opt/slack-api-export/var

  console:
    build:
      context: .
      dockerfile: Dockerfile.console
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./docker/slack_console:/opt/slack-api-export/var

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db

  tunnel:
    image: chuangbo/localtunnel
    links:
      - http
    command: lt -l http -p 8000 -s ${TUNNEL_HOSTNAME}
