version: '2'
services:

  base:
    build: .

  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    environment:
      - TUNNEL_HOSTNAME
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
    depends_on:
      - base
    links:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./logs/http:/opt/slack-api-export/var/logs

  sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./logs/sync:/opt/slack-api-export/var/logs

  export:
    build:
      context: .
      dockerfile: Dockerfile.export
    depends_on:
      - base
    links:
      - mongo
    volumes:
      - ./logs/export:/opt/slack-api-export/var/logs
      - ./export:/opt/slack-api-export/var/export

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db

  tunnel:
    image: chuangbo/localtunnel
    links:
      - http
    command: lt -l http -p 8000 -s ${TUNNEL_HOSTNAME}
