version: '2'
services:
  superscript:
    build: .
    environment:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_REDIRECT_URI
      - SYMFONY_MONGODB_SERVER=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
     - ./mongo:/data/db
